name: Hprofile Actions
on: workflow_dispatch
jobs: 
  Testing:
     runs-on:  ubuntu-latest
     steps: 
       - name: code checkout
         run: actions/checkout@v4

       - name: Maven tests
         run: mvn test 
        
       - name: checkstyle tests
         run: mvn checkstyle:checkstyle

       
